# -*- coding: utf-8 -*-
"""DAA practical 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pOcEFjbZm80pvCeLb4ETktqxm6-bDuI5
"""

import time


# Matrix Chain Multiplication using Dynamic Programming
def matrix_chain_order(p):
    n = len(p) - 1

    # Cost table
    m = [[0] * (n + 1) for _ in range(n + 1)]

    # Split table
    s = [[0] * (n + 1) for _ in range(n + 1)]

    # length = length of matrix chain
    for length in range(2, n + 1):

        for i in range(1, n - length + 2):
            j = i + length - 1

            m[i][j] = float('inf')

            # Try all possible split positions
            for k in range(i, j):

                cost = (
                    m[i][k]
                    + m[k + 1][j]
                    + p[i - 1] * p[k] * p[j]
                )

                if cost < m[i][j]:
                    m[i][j] = cost
                    s[i][j] = k

    return m, s


# Function to find optimal parenthesization
def print_optimal_parenthesis(s, i, j):

    if i == j:
        return f"M{i}"

    k = s[i][j]

    left = print_optimal_parenthesis(s, i, k)
    right = print_optimal_parenthesis(s, k + 1, j)

    return f"({left} × {right})"


# ---------------- MAIN PROGRAM ----------------

print("CHAIN MATRIX MULTIPLICATION USING DYNAMIC PROGRAMMING")
print("-" * 60)

# Number of matrices
n = int(input("Enter the number of matrices: "))

dimensions = []

print("\nEnter the dimensions of the matrices:")

for i in range(n):

    rows = int(input(f"Enter number of rows of Matrix M{i + 1}: "))
    cols = int(input(f"Enter number of columns of Matrix M{i + 1}: "))

    # Check compatibility
    if i > 0 and dimensions[-1] != rows:
        print("\nError: Matrix dimensions are not compatible.")
        exit()

    if i == 0:
        dimensions.append(rows)

    dimensions.append(cols)


# Display matrix dimensions
print("\nMatrix Dimensions:")
for i in range(n):
    print(f"M{i + 1} = {dimensions[i]} × {dimensions[i + 1]}")


# Measure execution time
start_time = time.perf_counter()

m, s = matrix_chain_order(dimensions)

end_time = time.perf_counter()

execution_time = end_time - start_time


# ---------------- RESULTS ----------------

print("\nRESULT")
print("-" * 60)

print("Minimum number of scalar multiplications:", m[1][n])

print("Optimal Parenthesization:",
      print_optimal_parenthesis(s, 1, n))

print(f"Execution Time: {execution_time:.10f} seconds")


# ---------------- COST TABLE ----------------

print("\nCOST TABLE (M)")
print("-" * 60)

print("      ", end="")

for j in range(1, n + 1):
    print(f"M{j:>8}", end="")

print()

for i in range(1, n + 1):

    print(f"M{i:<3}", end="")

    for j in range(1, n + 1):

        if i > j:
            print(f"{'-':>10}", end="")
        elif i == j:
            print(f"{'0':>10}", end="")
        else:
            print(f"{m[i][j]:>10}", end="")

    print()


# ---------------- SPLIT TABLE ----------------

print("\nSPLIT TABLE (S)")
print("-" * 60)

print("      ", end="")

for j in range(1, n + 1):
    print(f"M{j:>8}", end="")

print()

for i in range(1, n + 1):

    print(f"M{i:<3}", end="")

    for j in range(1, n + 1):

        if i >= j:
            print(f"{'-':>10}", end="")
        else:
            print(f"{'M' + str(s[i][j]):>10}", end="")

    print()


# ---------------- COMPLEXITY ----------------

print("\nTIME COMPLEXITY")
print("-" * 60)

print("Best Case    : O(n^3)")
print("Average Case : O(n^3)")
print("Worst Case   : O(n^3)")

print("\nSPACE COMPLEXITY")
print("-" * 60)

print("O(n^2)")