# -*- coding: utf-8 -*-
"""DAA practical 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13DvkPygtc_MVfIX_iqLVe_lDZV8JN-CP
"""

import time
import sys

# Increase recursion limit for larger inputs
sys.setrecursionlimit(10000)


# ---------------- ITERATIVE METHOD ----------------
def factorial_iterative(n):
    fact = 1

    for i in range(1, n + 1):
        fact = fact * i

    return fact


# ---------------- RECURSIVE METHOD ----------------
def factorial_recursive(n):
    if n == 0 or n == 1:
        return 1

    return n * factorial_recursive(n - 1)


# ---------------- MAIN PROGRAM ----------------
print("==============================================")
print("   FACTORIAL: ITERATIVE vs RECURSIVE METHOD")
print("==============================================")

n = int(input("Enter a non-negative integer: "))

if n < 0:
    print("Factorial is not defined for negative numbers.")
    exit()


# -------- ITERATIVE IMPLEMENTATION --------
start_time = time.perf_counter()

iterative_result = factorial_iterative(n)

end_time = time.perf_counter()

iterative_time = end_time - start_time


# -------- RECURSIVE IMPLEMENTATION --------
start_time = time.perf_counter()

recursive_result = factorial_recursive(n)

end_time = time.perf_counter()

recursive_time = end_time - start_time


# -------- DISPLAY RESULTS --------
print("\n--------------- RESULTS ----------------")

print("Input (n):", n)

print("\nIterative Method:")
print("Factorial =", iterative_result)
print("Implementation Time = {:.10f} seconds".format(iterative_time))

print("\nRecursive Method:")
print("Factorial =", recursive_result)
print("Implementation Time = {:.10f} seconds".format(recursive_time))


# -------- TIME COMPLEXITY --------
print("\n--------------- TIME COMPLEXITY ----------------")

print("\nIterative Method:")
print("Best Case    : O(n)")
print("Average Case : O(n)")
print("Worst Case   : O(n)")

print("\nRecursive Method:")
print("Best Case    : O(n)")
print("Average Case : O(n)")
print("Worst Case   : O(n)")


# -------- SPACE COMPLEXITY --------
print("\n--------------- SPACE COMPLEXITY ----------------")

print("Iterative Method : O(1)")
print("Recursive Method : O(n)")


# -------- COMPARISON --------
print("\n--------------- COMPARISON ----------------")

if iterative_time < recursive_time:
    print("Iterative method was faster for this execution.")
elif recursive_time < iterative_time:
    print("Recursive method was faster for this execution.")
else:
    print("Both methods took approximately the same time.")

print("\nNote: Actual execution time may vary depending")
print("on the computer, Python version, and system load.")