# -*- coding: utf-8 -*-
"""DAA practical 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYEi8P-Pt3EBMldPhAhuOB-bIz4qAttI
"""

import time

# ---------------- DYNAMIC PROGRAMMING FUNCTION ----------------
def coin_change(coins, amount):

    # DP array initialized with infinity
    dp = [float('inf')] * (amount + 1)

    # To store selected coins
    used_coin = [-1] * (amount + 1)

    dp[0] = 0

    for i in range(1, amount + 1):
        for coin in coins:

            if coin <= i:
                if dp[i - coin] + 1 < dp[i]:
                    dp[i] = dp[i - coin] + 1
                    used_coin[i] = coin

    # If no solution exists
    if dp[amount] == float('inf'):
        return -1, []

    # Find coins used
    result = []
    temp = amount

    while temp > 0:
        result.append(used_coin[temp])
        temp -= used_coin[temp]

    return dp[amount], result


# ---------------- MAIN PROGRAM ----------------
print("=======================================")
print("   MAKING CHANGE USING DYNAMIC PROGRAMMING")
print("=======================================")

# User input
n = int(input("Enter number of coin denominations: "))

coins = []

for i in range(n):
    coin = int(input(f"Enter coin {i+1}: "))
    coins.append(coin)

amount = int(input("Enter amount to make: "))

# -------- START TIMER --------
start = time.perf_counter()

min_coins, coin_list = coin_change(coins, amount)

# -------- END TIMER --------
end = time.perf_counter()

execution_time = end - start

# ---------------- OUTPUT ----------------
print("\n----------- RESULT -----------")

if min_coins == -1:
    print("No solution possible.")
else:
    print("Minimum coins required:", min_coins)
    print("Coins used:", coin_list)

print("\nImplementation Time: {:.10f} seconds".format(execution_time))


# ---------------- COMPLEXITY ----------------
print("\n----------- TIME COMPLEXITY -----------")

print("Best Case    : O(A × N)")
print("Average Case : O(A × N)")
print("Worst Case   : O(A × N)")

print("\nWhere:")
print("A = Amount")
print("N = Number of coin denominations")

print("\n----------- SPACE COMPLEXITY -----------")
print("Space Complexity: O(A)")

print("\n----------- NOTE -----------")
print("Actual execution time depends on system performance.")