# -*- coding: utf-8 -*-
"""practical_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1viJPuMWVZQfSW6MusWZm0vVSXsrcbZnv

Maxheap sorting
---------------
"""

import time

# Function to maintain Max Heap
def heapify(arr, n, i):
    largest = i
    left = 2 * i + 1
    right = 2 * i + 2

    # Check left child
    if left < n and arr[left] > arr[largest]:
        largest = left

    # Check right child
    if right < n and arr[right] > arr[largest]:
        largest = right

    # If largest is not the root
    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i]

        # Recursively heapify
        heapify(arr, n, largest)


# Heap Sort function
def heap_sort(arr):
    n = len(arr)

    # Step 1: Build Max Heap
    for i in range(n // 2 - 1, -1, -1):
        heapify(arr, n, i)

    # Step 2: Extract elements one by one
    for i in range(n - 1, 0, -1):

        # Move largest element to the end
        arr[0], arr[i] = arr[i], arr[0]

        # Heapify remaining elements
        heapify(arr, i, 0)


n = int(input("Enter the number of elements: "))

arr = list(map(int, input("Enter the elements separated by spaces: ").split()))

# Check number of elements
if len(arr) != n:
    print("Error: Please enter exactly", n, "elements.")

else:
    print("\nOriginal Array:")
    print(arr)

    # Measure execution time
    start_time = time.perf_counter()

    heap_sort(arr)

    end_time = time.perf_counter()

    # Calculate execution time
    execution_time = end_time - start_time

    print("\nSorted Array:")
    print(arr)

    print("\nExecution Time:")
    print(execution_time, "seconds")

    print("\nTime Complexity:")
    print("Best Case    : O(n log n)")
    print("Average Case : O(n log n)")
    print("Worst Case   : O(n log n)")

    print("\nSpace Complexity:")
    print("O(log n)")