# -*- coding: utf-8 -*-
"""PRACTICAL -2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IJJTJtkhd_RScERt6Lxg19TB-M0Sd0kJ

PRACTICAL - 2

1)Linear Search
"""

import time

# Take number of elements from user
n = int(input("Enter the number of elements: "))

# Take array elements from user
arr = []

print("Enter the elements:")
for i in range(n):
    element = int(input(f"Element {i + 1}: "))
    arr.append(element)

# Take element to search
key = int(input("Enter the element to search: "))

# Start execution time
start_time = time.perf_counter()

# Linear Search
found = False
comparisons = 0

for i in range(n):
    comparisons += 1

    if arr[i] == key:
        print("\nElement found at index:", i)
        found = True
        break

# If element is not found
if not found:
    print("\nElement not found")

# End execution time
end_time = time.perf_counter()

# Calculate execution time
execution_time = end_time - start_time

# Display results
print("\n----- Linear Search Analysis -----")

print("Number of comparisons:", comparisons)

print("Actual Execution Time:",
      execution_time, "seconds")

print("\nTime Complexity:")
print("Best Case    : O(1)")
print("Average Case : O(n)")
print("Worst Case   : O(n)")

print("\nSpace Complexity: O(1)")

"""2)Binary Search"""

import time

# Take number of elements from user
n = int(input("Enter the number of elements: "))

# Take array elements from user
arr = []

print("Enter the elements in sorted order:")
for i in range(n):
    element = int(input(f"Element {i + 1}: "))
    arr.append(element)

# Take element to search
key = int(input("Enter the element to search: "))

# Start execution time
start_time = time.perf_counter()

# Binary Search
low = 0
high = n - 1
found = False
comparisons = 0

while low <= high:
    mid = (low + high) // 2
    comparisons += 1

    if arr[mid] == key:
        print("\nElement found at index:", mid)
        found = True
        break

    elif arr[mid] < key:
        low = mid + 1

    else:
        high = mid - 1

# If element is not found
if not found:
    print("\nElement not found")

# End execution time
end_time = time.perf_counter()

# Calculate execution time
execution_time = end_time - start_time

# Display results
print("\n----- Binary Search Analysis -----")
print("Number of comparisons:", comparisons)
print("Actual Execution Time:", execution_time, "seconds")

# Display Time Complexity
print("\nTime Complexity:")
print("Best Case    : O(1)")
print("Average Case : O(log n)")
print("Worst Case   : O(log n)")

# Display Space Complexity
print("\nSpace Complexity: O(1)")